sudo: required
services:
    - docker

before_install:
    - docker build -t coupdevent/react-test -f ./client/Dockerfile.dev ./client
    
script:
    - docker run coupdevent/react-test npm test -- --coverage
    
after_success:
    - docker build - t coupdevent/multi-client ./client    
    - docker build - t coupdevent/multi-nginx ./nginx
    - docker build - t coupdevent/multi-server ./server 
    - docker build - t coupdevent/multi-worker ./worker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push coupdevent/multi-client
    - docker push coupdevent/multi-nginx
    - docker push coupdevent/multi-server
    - docker push coupdevent/multi-worker


